version: '2'

services:
    haproxy_rabbitmq:
      build: ./
      container_name: haproxy_rabbitmq
      privileged: true

      ports:
         - "5670:5670"
         - "8000:8000"
      network_mode: host
      volumes:
        #workdir
        - ../:/apps
        #配置日志文件的一部分，剩下的在start.sh内
        - ./conf/syslog/haproxy.conf:/etc/rsyslog.d/haproxy.conf
        - ../logs:/var/log

        #consul-template
        - ./consul-template:/consul-template
        - ./consul-template/consul-template:/usr/local/bin/consul-template:ro

        #sh 目录
        - ./sh:/sh:ro
        - ./supervisor:/supervisor

      command: /usr/local/bin/supervisord -n -c /supervisor/conf.d/supervisord.conf


